name: "Build & Deploy"

on:
  push:
    branches:
      - "main"
      - "cicd/initial-pipeline-implementation" # TODO: REMOVE THIS! - ONLY USING THIS FOR TESTING!

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@4

      - name: "Install Node"
        uses: actions/setup-node@4

      - name: "Install Node Dependencies"
        run: "npm install"

      - name: "Build Site"
        run: "npm run build"

      - name: "Publish Site Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "MuxIt"
          path: "./dist"
